[build]
    base = "client/"
    functions = "functions"
    publish = "build"
    command = "npm run build"

[functions]
    directory = "functions/"

[[plugins]]
  package = "netlify-plugin-form-submissions"

  [plugins.inputs]
    # Get submissions for specific forms
    # e.g. "form-name"
    # e.g. ["form-name-1", "form-name-2"]
    # e.g. "ALL"
    # default: "ALL"
    formNames = "approved-comments"

    # the folder to recieve json files for each form
    dataDirectory = "src/_data"